name: Common Test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['23.1']
        os: [ubuntu-latest]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2

    - uses: bajankristof/setup-erlang@master
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Common Test tests
      run: rebar3 ct --cover
    - name: Dialyzer
      run: rebar3 dialyzer

    - name: Covertool
      if: ${{ always() }}
      run: rebar3 covertool generate
    - uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/jsonlog.covertool.xml
        env_vars: OTP_VERSION
        flags: sdk,erlang
